name: aws destroy

on:
  workflow_dispatch:

jobs:
  aws-destroy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/aws-setup
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: terraform destroy
        run: bash -c "terraform init -backend-config=\"./env/backend.conf\" -reconfigure && terraform destroy -auto-approve --var-file=env/default.tfvars"
        working-directory: ./aws
